format_version: v1.0
configName: samc21_xpl
folderName: samc21_f
frameworkPath: C:\Test\h3_test
processor: ATSAMC21J18A
projectName: samc21_f
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMC21_DFP\3.8.119\samc21\atdf\ATSAMC21J18A.atdf
